config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  post '/login'=> 'sessions#create'
  get '/logout'=> 'sessions#destroy'

  resources :users
  resources :task_lists do 
    resources :tasks do
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :title, :description,
            :due_date, presence: true
  belongs_to :task_list
end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  validates :title, :user_id, presence: true
  belongs_to :user
  has_many :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password, :email, :display_name, presence: true
  validates :username, uniqueness: true
  validates :email, uniqueness: true

  has_many :task_lists

  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in!"
      redirect_to task_lists_path
    else
      flash[:errors] = "Invalid login. Please try again."
      redirect_to :back
    end
  end

  def destroy
    session.clear
    flash[:danger] = "You've logged out!"
    redirect_to root_path
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  
  def index
    @archived = current_user.task_lists.where(archived:true)
    @unarchived = current_user.task_lists.where(archived:false)
  end

  def new
    @task_list = current_user.task_lists.new
  end

  def create
    @task_list = current_user.task_lists.new(task_list_params)
    
    if @task_list.save
      flash[:success] = "New task list created!"
      redirect_to task_lists_path
    else
      render :new 
    end
  end

  def edit
    @task_list = TaskList.find(params[:id])
  end

  def update
    @task_list = TaskList.find(params[:id])
    if @task_list.update(task_list_params)
      flash[:success] = "List updated!"
      redirect_to task_lists_path
    else
      flash[:warning] = "Oops! Try again."
      redirect_to :back
    end
  end

  def destroy
    @task_list = TaskList.find(params[:id])
    @task_list.destroy
    redirect_to task_lists_path
    flash[:warning] = "Bye bye #{@task_list.title}!"
  end

  private
  def task_list_params
    params.require(:task_list).permit(:title, :archived)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    # tasks = Task.where(task_list_id: params[:id])
    task_list   = TaskList.find(params[:task_list_id])
    @incomplete = task_list.tasks.where(completed:false)
    @completed  = task_list.tasks.where(completed: true)
  end

  def new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    task_list = TaskList.find(params[:task_list_id])
    @task = task_list.tasks.new(task_params)

    if @task.save 

      email_matchdata = @task.title.match(/\/cc (.+)/)
      if email_matchdata
        email = email_matchdata[1] 

        TaskMailer.create(email, @task).deliver_later
        flash[:notice] = "Your email has been sent!"
      end

        flash[:success] = "New task created!"
        redirect_to task_list_tasks_path
    else
        render :new 
    end
  end

  def update
    @task = Task.find(params[:id])
    if request.xhr?   #if an ajax request
      if @task.update(task_params)
        render nothing:true
      else
        render nothing:true, status: 422
      end
    else
      if @task.update(task_params)
        flash[:success] = "Task updated!"
        redirect_to task_list_tasks_path
      else
        flash[:warning] = "Oops! Try again."
        redirect_to :back
      end
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :completed, :description, :due_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account created!"
      redirect_to task_lists_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit( :username, :email, 
                                  :password, :display_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<h1 class="center-header"> Welcome to the Task List Maker </h1>

app/views/layouts/_navbar.html.erb
<nav class='navbar navbar-inverse navbar-fixed-top' role='navigation'>
         <% if current_user %>
         <span class="username-correction navbar-form navbar-left pull-left"> Welcome <%= current_user.display_name %>!</span>
         <% end %>
  <div class='container-fluid'>
    <div class='navbar-form navbar-right' role='search'>
      <div class='navbar-header'>
        <ul class="nav navbar-nav" id="login"> 
        <% if current_user.nil? %>
          <li> <%= link_to "Home", root_path %> </li>
          <li> <%= link_to "Sign Up", new_user_path %> </li>
          <li>  <%= render 'sessions/new' %> </li>
        </ul>
      </div>
        <% else %>
      <div class='navbar-form navbar-right' role='search'>
        <ul class="nav navbar-nav" id="logout"> 
     
          <li> <%= link_to "Home", root_path %> </li>
          <li> <%= link_to "My Lists", task_lists_path %> </li>
          <li> <%= link_to "Logout", logout_path %> </li>
      <% end %>
        </ul> 
  
      </div>
    </div>
  </div>
</nav>
<div id='name' style='margin-top:70px'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskList</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<%= render 'layouts/navbar' %>
<%= render 'partials/flash_messages' %>
<body>
<div class="container">
  <%= yield %>
</div>

</body>

</html>

app/views/partials/_flash_messages.html.erb
<div class="flash">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: "alert alert-#{name} text-center" %>
  <% end %>
</div>

app/views/partials/_task_errors.html.erb
<% if @task && @task.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
    The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_task_list_errors.html.erb
<% if @task_list && @task_list.errors.any? %>
  <div id="error_explatasknation">
    <div class="alert alert-danger">
    The form contains <%= pluralize(@task_list.errors.count, "error") %>.
    </div>
    <ul>
      <% @task_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
task

app/views/partials/_user_errors.html.erb
<% if @user && @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
    The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/task_lists/_archived.html.erb
<h3> Archived Lists </h3>
<table class="table table-condensed table-striped" id="archived">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archived.reverse.each do |list| %>
      <tr>
        <td><%= link_to list.title, task_list_tasks_path(list.id) %></td>
        <td><%= link_to 'Edit', edit_task_list_path(list.id)%></td>
        <td><%= link_to 'Delete', task_list_path(list.id), method: :delete, data: { confirm: "Are you sure you want to delete this list?" }%></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/task_lists/_form.html.erb
<div class="col-xs-6">
    <div class="form">

        <%= form_for(:task_list, url: task_lists_path, method: :post, role:"form") do |f| %>

          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%><br>

        <div>
          <%= f.submit "Create A Task List", id: "check-in", class: "btn btn-primary" %>
        </div>
        <% end %>
    </div>  
</div>

app/views/task_lists/edit.html.erb
<h1> Edit Task List <%= @task_list.title %></h1>
<div class="col-xs-6">
    <div class="form">

        <%= form_for(@task_list, url: task_list_path, method: :patch, role:"form") do |f| %>

          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%><br>

          <div>
            <%= f.label :archived %>
            <%= f.check_box :archived %>
          </div>

        <div>
          <%= f.submit "Update", class: "btn btn-primary" %>
        </div>
        <% end %>
    </div>  
</div>

app/views/task_lists/index.html.erb
<h3> <%= current_user.display_name %>'s List of Things to Do </h3>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unarchived.reverse.each do |list| %>
      <tr>
        <td><%= link_to list.title, task_list_tasks_path(list.id) %></td>
        <td><%= link_to 'Edit', edit_task_list_path(list.id)%></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <%= render 'task_lists/archived' %>



<%= link_to 'Create A New Task List', new_task_list_path, class: 'btn btn-default btn-s' %><br><br>

app/views/task_lists/new.html.erb
<div class="col-xs-6">
    <div class="form">
      <h1>Create A Task List</h1>

        <%= form_for(:task_list, url: task_lists_path, method: :post, role:"form") do |f| %>

        <%= render "partials/task_list_errors" %>

        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control"%><br>

        <div>
          <%= f.label :archived %>
          <%= f.check_box :archived %>
        </div>

          <div>
            <%= f.submit "Add List", class: "btn btn-primary" %>
          </div>
        <% end %>
    </div>  
</div>`

app/views/tasks/_completed.html.erb
 <h3> Completed Tasks </h3>
<table class="table table-bordered table-condensed table-striped tasks complete">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Due Date</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @completed.reverse.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= link_to 'Edit', edit_task_list_task_path(params[:task_list_id], task.id) %></td>
        <td><input type="checkbox" class="task-status" data-url="<%= task_list_task_path(task.task_list, task) %>"</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/edit.html.erb
<div class="col-xs-6">
    <div class="form">
      <h3>Edit Task </h3>

        <%= form_for(@task, url: task_list_task_path(@task.task_list_id ,@task.id), method: :patch, role:"form") do |f| %>
         <%= render "partials/task_errors" %>

          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%><br>

          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control"%><br>

          <%= f.label :due_date %>
          <%= f.date_field :due_date, class: "form-control"%><br>

          <div>
            <%= f.label :completed %>
            <%= f.check_box :completed %>
          </div>

          <div>
            <%= f.submit "Update Task", class: "btn btn-primary" %>
          </div>
        <% end %>
    </div>  
</div>

app/views/tasks/index.html.erb
<h3> Current Tasks</h3>

<table class="table table-bordered table-condensed table-striped incomplete tasks">
  <thead>
    <tr>
      <th>Title</th>
      <th >Description</th>
      <th>Due Date</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @incomplete.reverse.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.due_date %></td>
        <td><%= link_to 'Edit', edit_task_list_task_path(params[:task_list_id], task.id) %></td>
        <td> <input type="checkbox" class="task-status" data-url="<%= task_list_task_path(task.task_list, task) %>"></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'tasks/completed' %><br><br>   

<%= link_to 'Create A New Task', new_task_list_task_path, class: 'btn btn-default btn-s' %><br><br>

app/views/tasks/new.html.erb
<div class="col-xs-6">
    <div class="form">
      <h2>Create A New Task </h2> 

        <%= form_for(:task, url: task_list_tasks_path, method: :post, role:"form") do |f| %>
         <%= render "partials/task_errors" %>

          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control"%><br>

          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control"%><br>

          <%= f.label :due_date %>
          <%= f.date_field :due_date, class: "form-control"%><br>

          <div>
            <%= f.label :completed %>
            <%= f.check_box :completed %>
          </div>

          <div>
            <%= f.submit "Add Task", class: "btn btn-primary" %>
          </div>
        <% end %>
    </div>  
</div>

app/views/users/new.html.erb
<div class="col-xs-12"> 
  <div class="col-xs-6">
    <div class="form">
      <h1>Create Acount</h1>

        <%= form_for(:user, url: users_path, method: :post, role:"form") do |f| %>
        <%= render "partials/user_errors" %>

        <%= f.label :username %>
        <%= f.text_field :username, class: "form-control"%>

        <%= f.label :display_name %>
        <%= f.text_field :display_name, class: "form-control" %>

        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label :password_confirmation, "Password Confirmation" %>
        <%= f.password_field :password_confirmation, class: "form-control" %><br>

      <div>
        <%= f.submit "Create Account", id: "check-in", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>